const mainMenu = [
	{ number: 1, text: "Place An Order" },
	{ number: 2, text: "Checkout Order" },
	{ number: 3, text: "order history" },
	{ number: 4, text: "Check Current Order" },
	{ number: 0, text: "Cancel Order" },
];

const foodMenu = [  
	{ number: 1,  food: "Idly(2):                    20rs"},
	{ number: 2,  food: "Mini Idly                  125rs",},
	{ number: 3,  food: "Sambar Idly:               50rs",},
	{ number: 4,  food: "Thatte Idly:              50rs",},
	{ number: 5,  food: "Fry Idly:                  40rs",},
	{ number: 6,  food: "Plain Dosa:                40rs",},
	{ number: 7,  food: "Masala Dosa:               65rs",},
	{ number: 8,  food: "Ghee Dosa:                 55rs",},
	{ number: 9,  food: "Onion Dosa:                60rs",},
	{ number: 10, food: "Onion Rava:                65rs",},
	{ number: 11, food: "Podi Dosa:                55rs",},
	{ number: 12, food: "Pongal:                   40rs",},
	{ number: 13, food: "Poori(2):                 45rs",},
	{ number: 14, food: "Chola poori(1):           75rs",},
	{ number: 15, food: "Chapathi(2):              30rs",},
	{ number: 16, food: "Idiyappam(2):             25rs",},
	{ number: 17, food: "Upma:                     25rs",},
	{ number: 18, food: "Medu Vada(1):             10rs",},
	{ number: 19, food: "Masala Vada(1):           10rs",},
	{ number: 20, food: "Bonda(1):                 10rs",},
	{ number: 21, food: "Tea:                      15rs",},
	{ number: 22, food: "Coffee:                   20rs",},
	{ number: 23, food: "Unlimited Meals:         125rs",},
	{ number: 24, food: "Mini Meals:               75rs",},
	{ number: 25, food: "Special Meals:           100rs",},
	{ number: 26, food: "Sambar Rice:              40rs",},
	{ number: 27, food: "Lemon Rice:               30rs",},
	{ number: 28, food: "Curd Rice:                30rs",},
	{ number: 29, food: "Tomato Rice:              30rs",},
	{ number: 30, food: "veg.Brinji:               45rs",},
	{ number: 31, food: "Chicken Biryani:         120rs",},
	{ number: 32, food: "Mutton Biryani:          180rs",},
	{ number: 33, food: "plain Biryani:            90rs",},
	{ number: 34, food: "veg.Fried Rice:           90rs",},
	{ number: 35, food: "Ch.Fried Rice:           120rs",},
	{ number: 36, food: "Egg Fried Rice:          100rs",},
	{ number: 37, food: "Veg.Noodles:              90rs",},
	{ number: 38, food: "Ch. Noodles:             110rs",},
	{ number: 39, food: "Egg Noodles:             100rs",},
	{ number: 40, food: "Chilli Chicken:          120rs",},
	{ number: 41, food: "Chicken 65:              150rs",},
	{ number: 42, food: "Pepper Chicken:          130rs",},
	{ number: 43, food: "Ch. Manchurian:          150rs",},
	{ number: 44, food: "Gobi Manchurian:         100rs",},
	{ number: 45, food: "Dragon Chicken:          150rs",},
	{ number: 46, food: "Chicken wings:           180rs",},
	{ number: 47, food: "Chicken Tikka:           150rs",},
	{ number: 48, food: "Periperi Chicken:       180rs",},
	{ number: 49, food: "Chicken Gravy:           130rs",},
	{ number: 50, food: "Butter Chicken:          160rs",},
	{ number: 51, food: "Mutton Curry:            200rs",},
	{ number: 52, food: "Mutton Keema:            220rs",},
	{ number: 53, food: "Fish Fry:                180rs",},
	{ number: 54, food: "prawn Fry:               180rs",},
	{ number: 55, food: "Fish Gravy:              180rs",},
	{ number: 56, food: "Prawn Gravy:             180rs",},
	{ number: 57, food: "Crab Gravy:              175rs",},
	{ number: 58, food: "Ch.Lollipop(6):          160rs",},
	{ number: 59, food: "Finger Fish:             170rs",},
	{ number: 60, food: "Ch.Nuggets:              150rs",},
	{ number: 61, food: "Vanilla IceCream:         80rs",},
	{ number: 62, food: "Chocobar:                 25rs",},
	{ number: 63, food: "choco IceCream:           90rs",},
	{ number: 64, food: "Butterscotch:             95rs",},
	{ number: 65, food: "Black Current:            90rs",},
	{ number: 66, food: "kesar Pista:              95rs",},
	{ number: 67, food: "Mango IceCream:           75rs",},
	{ number: 68, food: "Kulfi:                    60rs",},
	{ number: 69, food: "Gulab Jamun:              50rs",},
	{ number: 70, food: "Rasamalai:                65rs",},
	{ number: 71, food: "Kesari:                   40rs",},
	{ number: 72, food: "Mojito Classic:           90rs",},
	{ number: 73, food: "Lemon Soda:              35rs",},   

]
module.exports = {
	mainMenu,
	foodMenu,
};